# Generated by Django 4.2.7 on 2023-12-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='product',
            field=models.TextField(blank=True, null=True),
        ),
    ]
