# Generated by Django 4.2.7 on 2023-12-29 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_customer_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Price',
            new_name='price',
        ),
    ]
