# Generated by Django 4.2.7 on 2023-12-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_price_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='colorcode',
            field=models.CharField(max_length=100),
        ),
    ]
