# Generated by Django 4.2.7 on 2023-12-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_products_colorcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=200)),
                ('Types', models.CharField(max_length=100)),
                ('colorname', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('colorcode', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
