# Generated by Django 4.2.7 on 2024-01-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Items', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('sellingprice', models.IntegerField()),
            ],
        ),
    ]
