# Generated by Django 4.2.7 on 2024-01-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_employees_email_alter_employees_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='colorcode',
            field=models.CharField(max_length=100),
        ),
    ]
