# Generated by Django 4.2.7 on 2024-01-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_products_colorcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='colorcode',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
