# Generated by Django 4.2.7 on 2024-01-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_category_categoryname_alter_category_colorcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Items',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
