# Generated by Django 4.2.7 on 2024-01-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_stock_items_alter_stock_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Brand',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
