# Generated by Django 4.2.7 on 2024-01-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
