# Generated by Django 4.2.7 on 2024-01-17 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0031_invoice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invoice",
        ),
    ]
