# Generated by Django 4.2.7 on 2024-01-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0032_delete_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="invoiceDate",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="invoiceNumber",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
