# Generated by Django 4.2.7 on 2024-01-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0034_alter_customer_invoicedate"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
