# Generated by Django 4.2.7 on 2024-01-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0038_delete_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="date",
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
