# Generated by Django 4.2.7 on 2024-01-21 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0040_remove_purchase_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Purchase",
        ),
    ]
