# Generated by Django 4.2.7 on 2024-01-22 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0044_purchase_date_purchased"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchase",
            old_name="date_purchased",
            new_name="created_at",
        ),
    ]
