# Generated by Django 4.2.7 on 2024-01-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0045_rename_date_purchased_purchase_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
