# Generated by Django 4.2.7 on 2024-02-10 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0049_delete_purchase"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="product",
            new_name="Brand",
        ),
    ]
